{"name": "test_div[除数为0]", "status": "failed", "statusDetails": {"message": "AssertionError: 除数不能为0\nassert False", "trace": "self = <class_2_2_task.test_case.test_calculator.TestCalculator object at 0x000001C246B14948>, a = 1, b = 0, expect = '除数不能为0'\nget_clac = <class_2_2_task.python_code.Calculator.Calculator object at 0x000001C2468F9908>, logger = <RootLogger root (INFO)>\n\n    @allure.story(\"测试除法\")\n    @pytest.mark.parametrize('a, b, expect', div_data, ids=div_ids)\n    def test_div(self, a, b, expect, get_clac, logger):\n        if isinstance(a, (int, float)) and isinstance(b, (int, float)):\n            if b != 0:\n                # 计算结果，保留2位小数\n                actual = round(get_clac.div(a, b), 2)\n                logger.info(f\"预期值：{expect}, 实际值：{actual}\")\n                # 断言\n                assert actual == expect\n            else:\n>               assert False, \"除数不能为0\"\nE               AssertionError: 除数不能为0\nE               assert False\n\ntest_calculator.py:49: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "0"}, {"name": "expect", "value": "'除数不能为0'"}], "start": 1624789812534, "stop": 1624789812534, "uuid": "fa950f51-c656-44cb-8775-e25f980b3d95", "historyId": "aff27ed3de87ed51d8af252c4fd3a8ea", "testCaseId": "00f43c99e69edabe02f02364c544f882", "fullName": "test_calculator.TestCalculator#test_div", "labels": [{"name": "story", "value": "测试除法"}, {"name": "feature", "value": "计算器测试"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "LAPTOP-L0LUTPCQ"}, {"name": "thread", "value": "9648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}